# -*- coding: utf-8 -*-
"""Early Disease Detection from Lifestyle Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JX_5YiiQcgpWY1xz2URleZxxTUwn5Kmx

1. Introduction

Import libraries
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, roc_curve, confusion_matrix, r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.cluster import KMeans

import warnings
warnings.filterwarnings('ignore')

"""2. Dataset Description"""

# 2.1 Load dataset
df = pd.read_csv("/content/sample_data/Wellbeing_and_lifestyle_data_Kaggle.csv")  # replace filename if different
df.head()

# 2.2 Basic overview
print("Rows, columns:", df.shape)
df.info()
df.describe(include='all').T

"""Feature Types"""

# list feature types
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
print("Numeric cols:", num_cols)
print("Categorical cols:", cat_cols)

"""Correlation heatmap"""

plt.figure(figsize=(12,10))
sns.heatmap(df[num_cols].corr(), annot=False, cmap='RdBu', center=0)
plt.title("Correlation (numerical features)")
plt.show()

"""Class Distribution (Imbalance Check)"""

# Create a binary class for disease_risk based on WORK_LIFE_BALANCE_SCORE
median_score = df['WORK_LIFE_BALANCE_SCORE'].median()
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < median_score).astype(int)  # 1 for high risk (low score), 0 for low risk (high score)

# Count of each class
print("\nClass Distribution:")
print(df['disease_risk'].value_counts())

# Visual distribution
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(5,4))
sns.countplot(x='disease_risk', data=df, palette='Set2')
plt.title('Class Distribution (Imbalance Check)')
plt.xlabel('Disease Risk (0 = Low, 1 = High)')
plt.ylabel('Count')
plt.show()

# Create Binary Target: disease_risk
# High risk if BMI > 25 OR sleep_hours < 6 OR stress_level is High
# Check if 'BMI', 'Sleep hours', and 'Stress level' columns exist before creating 'disease_risk'
if 'BMI_RANGE' in df.columns and 'SLEEP_HOURS' in df.columns and 'DAILY_STRESS' in df.columns:
    df['disease_risk'] = ((df['BMI_RANGE'] > 1) | # Assuming BMI_RANGE 1 is normal, 2 is overweight
                          (df['SLEEP_HOURS'] < 6) |
                          (df['DAILY_STRESS'].astype(str) == 'High')).astype(int) # Convert to string for comparison
    # Quick check of target variable
    print("\nSample of 'disease_risk' column:")
    print(df[['BMI_RANGE', 'SLEEP_HOURS', 'DAILY_STRESS', 'disease_risk']].head())
else:
    print("Required columns for creating 'disease_risk' not found.")

"""EDA — Important relationships"""

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# 1. Summary & Missing Values
#print("=== Summary ===")
#print(df[['SLEEP_HOURS', 'DAILY_STRESS', 'WORK_LIFE_BALANCE_SCORE']].describe())
#print("\n=== Missing ===")
#print(df.isnull().sum())

# 2. Distributions
plt.figure(figsize=(6, 2))
plt.subplot(1, 2, 1)
sns.countplot(x='GENDER', data=df, palette='Set2')
plt.title('Gender')
plt.subplot(1, 2, 2)
sns.histplot(df['SLEEP_HOURS'], bins=10, color='teal')
plt.title('Sleep Hours')
plt.tight_layout()
plt.show()

# 3. Class Distribution
#print("\n=== Class Distribution ===")
#print(df['disease_risk'].value_counts())
plt.figure(figsize=(4, 3))
sns.countplot(x='disease_risk', data=df, palette='Set2')
plt.title('Disease Risk (0=Low, 1=High)')
plt.show()

# 4. Boxplot
plt.figure(figsize=(4, 3))
sns.boxplot(x='disease_risk', y='SLEEP_HOURS', data=df, palette='Set2')
plt.title('Sleep vs Risk')
plt.show()

print("Insights: More sleep (>7 hours) linked to lower disease risk.")

"""Density plots of numerical features"""

df[num_cols].hist(bins=20, figsize=(14,10))
plt.tight_layout()
plt.show()

"""3. Dataset Pre-processing"""

# Drop unnecessary columns
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Check missing values
print("Missing Values:")
print(df.isnull().sum().sort_values(ascending=False))

# Class Distribution
print("\nClass Distribution:")
print(df['disease_risk'].value_counts())

"""Dropping unnecessary columns"""

# Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Class Distribution
print("Class Distribution:")
print(df['disease_risk'].value_counts())

print("Insight: More sleep (>7 hours) linked to lower disease risk.")

"""Encoding categorical variables"""

# Drop unnecessary columns
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')
# Define categorical columns
cat_cols = ['AGE', 'GENDER']

# Fill missing for categorical -> mode
cat_imputer = SimpleImputer(strategy='most_frequent')
for c in cat_cols:
    if c in df.columns:
        df[c] = cat_imputer.fit_transform(df[c].values.reshape(-1, 1)).flatten()

# Label encode categorical columns
le = LabelEncoder()
for c in cat_cols:
    if c in df.columns:
        df[c] = le.fit_transform(df[c].astype(str))

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Check missing values
print("Missing Values:")
print(df[cat_cols + ['WORK_LIFE_BALANCE_SCORE']].isnull().sum())

# Class Distribution
print("\nClass Distribution:")
print(df['disease_risk'].value_counts())

"""Impute numeric missing values and feature scaling"""

# Numeric impute (mean)
num_imputer = SimpleImputer(strategy='mean')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

# Scaling later after target/feature split. For now, update numeric columns list (some may have changed)
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

"""Feature selection"""

features = df.drop(columns=['disease_risk'])
feature_names = features.columns.tolist()
print("Using features:", feature_names[:20])

"""Feature scaling"""

import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Convert DAILY_STRESS to numeric
if 'DAILY_STRESS' in df.columns:
    df['DAILY_STRESS'] = pd.to_numeric(df['DAILY_STRESS'], errors='coerce')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Define columns
cat_cols = ['AGE', 'GENDER']
num_cols = [col for col in df.columns if col not in cat_cols + ['disease_risk']]

# Impute missing
df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])
# Convert num_cols to numeric, coercing errors
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df[num_cols] = SimpleImputer(strategy='median').fit_transform(df[num_cols])

# Encode categorical
features = df.drop(columns=['disease_risk'])
encoder = OneHotEncoder(sparse_output=False)
cat_encoded = pd.DataFrame(
    encoder.fit_transform(features[cat_cols]),
    columns=encoder.get_feature_names_out(cat_cols)
)

# Combine and scale
X = StandardScaler().fit_transform(pd.concat([features[num_cols], cat_encoded], axis=1))
y = df['disease_risk'].values

# Output
print("Missing:", df.isnull().sum().sum())
print("Class Distribution:", pd.Series(y).value_counts())

"""4. Dataset Splitting"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

"""5. Model Training & Testing (KNN, Decision Tree, Logistic Regression, Naive Bayes, Neural Network) with Confusion Matrix"""

from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support

# Define models
models = {
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(max_iter=500, random_state=42)
}

# Train and evaluate each model
for name, model in models.items():
    print(f"\n====================== {name} ======================")
    # Fit model
    model.fit(X_train, y_train)
    # Predict
    y_pred = model.predict(X_test)

    # Store predictions in variables for later use in cell pCnxKZOLp6J6 and OGHKi7SFxuUU
    if name == "KNN":
        knn_pred = y_pred
        knn = model # store the trained model for ROC curve
    elif name == "Decision Tree":
        dt_pred = y_pred
        dt = model # store the trained model for ROC curve
    elif name == "Logistic Regression":
        lr_pred = y_pred
        lr = model # store the trained model for ROC curve
    elif name == "Naive Bayes":
        nb_pred = y_pred
        nb = model # store the trained model for ROC curve
    elif name == "Neural Network":
        nn_preds = y_pred
        nn = model # store the trained model for ROC curve
        # Also get probabilities for ROC curve if available
        if hasattr(model, "predict_proba"):
            nn_preds_prob = model.predict_proba(X_test)[:, 1]


    # Evaluation report
    print(classification_report(y_test, y_pred))
    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(4,3))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f'Confusion Matrix - {name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

"""6. Model Selection / Comparison Analysis

Bar Chart
"""

# Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Convert DAILY_STRESS
df['DAILY_STRESS'] = pd.to_numeric(df['DAILY_STRESS'], errors='coerce')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Define columns
cat_cols = ['AGE', 'GENDER']
num_cols = [col for col in df.columns if col not in cat_cols + ['disease_risk']]

# Impute and encode
df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])
df[num_cols] = SimpleImputer(strategy='median').fit_transform(df[num_cols].apply(pd.to_numeric, errors='coerce'))
X = StandardScaler().fit_transform(
    pd.concat([df[num_cols], pd.DataFrame(
        OneHotEncoder(sparse_output=False).fit_transform(df[cat_cols]),
        columns=OneHotEncoder(sparse_output=False).fit(df[cat_cols]).get_feature_names_out(cat_cols)
    )], axis=1)
)
y = df['disease_risk'].values

# Train models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
models = {
    'KNN': KNeighborsClassifier(),
    'DT': DecisionTreeClassifier(),
    'LR': LogisticRegression(),
    'NB': GaussianNB(),
    'NN': MLPClassifier(max_iter=1000)
}
models_acc = {k: accuracy_score(y_test, m.fit(X_train, y_train).predict(X_test)) for k, m in models.items()}

# Bar chart
plt.figure(figsize=(5, 2))
sns.barplot(x=list(models_acc.values()), y=list(models_acc.keys()))
plt.xlabel("Accuracy")
plt.xlim(0, 1)
plt.title("Model Accuracy")
plt.show()

# Output
print("Acc:", {k: f"{v:.2f}" for k, v in models_acc.items()})

"""Precision and Recall Comparison"""

# Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Convert DAILY_STRESS
df['DAILY_STRESS'] = pd.to_numeric(df['DAILY_STRESS'], errors='coerce')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Define columns
cat_cols = ['AGE', 'GENDER']
num_cols = [col for col in df.columns if col not in cat_cols + ['disease_risk']]

# Impute and encode
df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])
df[num_cols] = SimpleImputer(strategy='median').fit_transform(df[num_cols].apply(pd.to_numeric, errors='coerce'))
X = StandardScaler().fit_transform(
    pd.concat([df[num_cols], pd.DataFrame(
        OneHotEncoder(sparse_output=False).fit_transform(df[cat_cols]),
        columns=OneHotEncoder(sparse_output=False).fit(df[cat_cols]).get_feature_names_out(cat_cols)
    )], axis=1)
)
y = df['disease_risk'].values

# Train models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
models = {
    'KNN': KNeighborsClassifier(),
    'DT': DecisionTreeClassifier(),
    'LR': LogisticRegression(),
    'NB': GaussianNB(),
    'NN': MLPClassifier(max_iter=1000)
}
preds = {k: m.fit(X_train, y_train).predict(X_test) for k, m in models.items()}

# Precision and Recall
def prec_rec(model_pred, y_true):
    p, r, _, _ = precision_recall_fscore_support(y_true, model_pred, average='binary', zero_division=0)
    return p, r

pr_data = {k: prec_rec(pred, y_test) for k, pred in preds.items()}
pr_df = pd.DataFrame(pr_data, index=['Precision', 'Recall']).T

# Bar chart with legend on side
pr_df.plot(kind='bar', figsize=(5, 2), color=['blue', 'orange'])
plt.title("Precision & Recall")
plt.ylim(0, 1)
plt.legend(['Precision', 'Recall'], loc='center left', bbox_to_anchor=(1, 0.5))
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Output
print(pr_df.round(2))

"""ROC Curves and AUC"""

# Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Convert DAILY_STRESS
df['DAILY_STRESS'] = pd.to_numeric(df['DAILY_STRESS'], errors='coerce')

# Create disease_risk
df['disease_risk'] = (df['WORK_LIFE_BALANCE_SCORE'] < df['WORK_LIFE_BALANCE_SCORE'].median()).astype(int)

# Define columns
cat_cols = ['AGE', 'GENDER']
num_cols = [col for col in df.columns if col not in cat_cols + ['disease_risk']]

# Impute and encode
df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])
df[num_cols] = SimpleImputer(strategy='median').fit_transform(df[num_cols].apply(pd.to_numeric, errors='coerce'))
X = StandardScaler().fit_transform(
    pd.concat([df[num_cols], pd.DataFrame(
        OneHotEncoder(sparse_output=False).fit_transform(df[cat_cols]),
        columns=OneHotEncoder(sparse_output=False).fit(df[cat_cols]).get_feature_names_out(cat_cols)
    )], axis=1)
)
y = df['disease_risk'].values

# Train models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
models = {
    'KNN': KNeighborsClassifier(),
    'DT': DecisionTreeClassifier(),
    'LR': LogisticRegression(),
    'NB': GaussianNB(),
    'NN': MLPClassifier(max_iter=1000)
}
models_fitted = {k: m.fit(X_train, y_train) for k, m in models.items()}
probas = {k: m.predict_proba(X_test)[:, 1] if hasattr(m, 'predict_proba') else None for k, m in models_fitted.items()}

# ROC Curves
plt.figure(figsize=(5, 4))
for name, prob in probas.items():
    if prob is not None:
        fpr, tpr, _ = roc_curve(y_test, prob)
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves")
plt.legend(loc='lower right')
plt.show()

# Output AUC
auc_scores = {k: auc(roc_curve(y_test, p)[0], roc_curve(y_test, p)[1]) if p is not None else None for k, p in probas.items()}
print("AUC Scores:", {k: f"{v:.2f}" if v is not None else "N/A" for k, v in auc_scores.items()})

"""Regression Model Training & Testing (R² Score and MSE)"""

#Drop Timestamp
df.drop(columns=['Timestamp'], inplace=True, errors='ignore')

# Convert DAILY_STRESS
df['DAILY_STRESS'] = pd.to_numeric(df['DAILY_STRESS'], errors='coerce')

# Check target
reg_target = next((c for c in ['self_reported_health', 'wellbeing_score', 'health_score', 'health']
                  if c in df.columns and np.issubdtype(df[c].dtype, np.number)), None)

if reg_target:
    print("Target:", reg_target)
    X_reg = df.drop(columns=[reg_target, 'disease_risk'])
    y_reg = df[reg_target].values
    Xr_train, Xr_test, yr_train, yr_test = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
    cat_cols = ['AGE', 'GENDER']
    num_cols = [c for c in X_reg.columns if c not in cat_cols]
    X_reg[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(X_reg[cat_cols])
    X_reg[num_cols] = SimpleImputer(strategy='median').fit_transform(X_reg[num_cols].apply(pd.to_numeric, errors='coerce'))
    X_reg = StandardScaler().fit_transform(pd.concat([X_reg[num_cols], pd.DataFrame(
        OneHotEncoder(sparse_output=False).fit_transform(X_reg[cat_cols]),
        columns=OneHotEncoder(sparse_output=False).fit(X_reg[cat_cols]).get_feature_names_out(cat_cols))], axis=1))
    rfr = RandomForestRegressor(n_estimators=100, random_state=42)
    rfr.fit(Xr_train, yr_train)
    yr_pred = rfr.predict(Xr_test)
    print("R2:", r2_score(yr_test, yr_pred))
    print("MSE:", mean_squared_error(yr_test, yr_pred))
else:
    print("No target found.")

"""Save cleaned dataset"""

# Save cleaned dataframe (with disease_risk)
df.to_csv("cleaned_lifestyle_wellbeing.csv", index=False)
print("Saved cleaned_lifestyle_wellbeing.csv")